const staff=['ちあき','スタッフ2','スタッフ3','スタッフ4','スタッフ5','スタッフ6','スタッフ7','スタッフ8'];
const shifts=['日勤','遅番','有休','半/休','半/振','有/振','振/振','特休','夏休','冬休','—'];
const roles=['L','A','B','C','D','E','—'];
let cur=new Date(2026,9,1), selected={person:0,day:1};
let data=JSON.parse(localStorage.getItem('shift-room-data')||'{}');
const key=()=>`${cur.getFullYear()}-${String(cur.getMonth()+1).padStart(2,'0')}`;
function monthData(){data[key()]??={};return data[key()]}
function save(){localStorage.setItem('shift-room-data',JSON.stringify(data))}
function days(){return new Date(cur.getFullYear(),cur.getMonth()+1,0).getDate()}
function renderTable(){document.querySelector('#monthTitle').textContent=`${cur.getFullYear()}年 ${cur.getMonth()+1}月`;let h='<thead><tr><th class="name">NAME</th>';for(let d=1;d<=days();d++){let wd=new Date(cur.getFullYear(),cur.getMonth(),d).getDay();h+=`<th class="${wd===0?'sun':wd===6?'sat':''}">${d}<br>${'日月火水木金土'[wd]}</th>`}h+='</tr></thead><tbody>';staff.forEach((n,i)=>{h+=`<tr><td class="name" data-person="${i}">${n}</td>`;for(let d=1;d<=days();d++){let v=monthData()[`${i}-${d}`]||{};h+=`<td class="shiftCell" data-person="${i}" data-day="${d}"><div class="shiftMain">${v.shift||''}</div><div class="role">${v.role||''}</div></td>`}h+='</tr>'});h+='</tbody>';let t=document.querySelector('#shiftTable');t.innerHTML=h;t.querySelectorAll('.shiftCell').forEach(x=>x.onclick=()=>openPicker(+x.dataset.person,+x.dataset.day));t.querySelectorAll('.name[data-person]').forEach(x=>x.onclick=()=>showPersonal(+x.dataset.person))}
function openPicker(p,d){selected={person:p,day:d};document.querySelector('#pickTitle').textContent=`${staff[p]}・${d}日`;picker.showModal()}
shiftChoices.innerHTML=shifts.map(x=>`<button value="${x}">${x}</button>`).join('');roleChoices.innerHTML=roles.map(x=>`<button value="${x}">${x}</button>`).join('');
shiftChoices.querySelectorAll('button').forEach(b=>b.onclick=e=>{e.preventDefault();let k=`${selected.person}-${selected.day}`;monthData()[k]??={};monthData()[k].shift=b.value==='—'?'':b.value;save();renderTable();renderPersonal()});roleChoices.querySelectorAll('button').forEach(b=>b.onclick=e=>{e.preventDefault();let k=`${selected.person}-${selected.day}`;monthData()[k]??={};monthData()[k].role=b.value==='—'?'':b.value;save();renderTable()});
function showPersonal(i){selected.person=i;document.querySelector('[data-view="personal"]').click();personSelect.value=i;renderPersonal()}
function renderPersonal(){let i=+personSelect.value||0;personalName.textContent=`${staff[i]}'S SHIFT`;engMonth.textContent=new Intl.DateTimeFormat('en',{month:'long',year:'numeric'}).format(cur);let first=new Date(cur.getFullYear(),cur.getMonth(),1).getDay();let html='';['SUN','MON','TUE','WED','THU','FRI','SAT'].forEach(x=>html+=`<div class="dow">${x}</div>`);for(let j=0;j<first;j++)html+='<div class="calCell"></div>';let counts={};for(let d=1;d<=days();d++){let v=monthData()[`${i}-${d}`]?.shift||'';if(v)counts[v]=(counts[v]||0)+1;html+=`<div class="calCell"><div class="daynum">${d}</div>${v?`<span class="badge">${v}</span>`:''}</div>`}calendar.innerHTML=html;summary.innerHTML=Object.entries(counts).map(([k,v])=>`<span class="sum">${k} ♡ ${v}</span>`).join('')}
function tabs(){document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));allView.hidden=b.dataset.view!=='all';personalView.hidden=b.dataset.view!=='personal';if(!personalView.hidden)renderPersonal()})}tabs();
personSelect.innerHTML=staff.map((x,i)=>`<option value="${i}">${x}</option>`).join('');personSelect.onchange=renderPersonal;prev.onclick=()=>{cur.setMonth(cur.getMonth()-1);renderTable();renderPersonal()};next.onclick=()=>{cur.setMonth(cur.getMonth()+1);renderTable();renderPersonal()};back.onclick=()=>document.querySelector('[data-view="all"]').click();document.querySelectorAll('.themes button').forEach(b=>b.onclick=()=>{personalCard.className=`personalCard ${b.dataset.theme}`;document.querySelector('.cardDecor').textContent=b.dataset.theme==='nurse'?'🩺 ♡ 💉 ✦':'🍦 ♡ ✦ 🍨'});
shareBtn.onclick=async()=>{alert('画像書き出しは次の実装で接続するよ♡ まず個人票の見た目を確認！')};renderTable();renderPersonal();

if('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js');
